project:
  type: website
  output-dir: docs

website:
  title: "ExMove.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true
    mainfont: Outfit

editor: visual

