project:
  type: website
  output-dir: docs

website:
  title: "ExMove"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right: 
      - icon: github
        href: https://github.com/ExMove/ExMove

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true
    mainfont: Outfit

editor: visual

