project:
  type: website
  output-dir: docs

website:
  title: "ExMove"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: User_guide.qmd
        text: User guide
      - href: Glossary.qmd
      - href: FAQs.qmd
      - href: Worked_example.qmd
        text: Example

    right: 
      - icon: github
        href: https://github.com/ExMove/ExMove

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true
    mainfont: Outfit

editor: visual

